### ISSUE TITLE
Output with certain commands doesn't return correct data.

### ISSUE THREAD

**Issue by anousonevongsouvanTR** [spenceation/hpnapy#21]
Hello there, several commands don't seem to work correctly such as the list_user, or list_diagnostic.  I am running HPNA version 2019.  However using the perl client api works fine.  Are there some commands that do not work correctly and is expected?  I can however run the list_device command in the python script, and get expected results.   

Sample script:

#!/usr/bin/python3

from hpnapy import NAInterface
import sys, getopt
import subprocess

# Initialize our interface
hpna = NAInterface("https://192.168.0.1", ssl_verify=False)
hpna.login('NA', 'xxxxx')

# Retrieve and iterate a list of device groups
device_groups = hpna.list_diagnostic(host="testdevice", diagnostic="NA OSPF Neighbors")
for line in device_groups:
     print(line

It doesn't return anything relevant for that command.  Output below:

{
    'CVE': None,
    'PowerScritCustFld1': None,
    'PowerScritCustFld2': None,
    'PowerScritCustFld3': None,
    'PowerScritCustFld4': None,
    'aCLID': None,
    'aCLType': None,
    'aaaPassword': None,
    'aaaUserName': None,
    'accessMethods': None,
    'accessTrigger': None,
    'actionTaken': None,
    'aggregatedPorts': None,
    'allowFailover': None,
    'application': None,
    'applicationState': None,
    'appliesToEntireDeviceFamily': None,
    'approvalPriority': None,
    'approvalStatus': None,
    'approvalUsers': None,
    'approveByDate': None,
    'assetTag': None,
    'associatedChannelID': None,
    'associatedChannelName': None,
    'associatedTable': None,
    'associatedTableID': None,
    'associatedUserGroupID': None,
    'associatedVlanID': None,
    'authenticationRuleID': None,
    'baseModelName': None,
    'blockEndPattern': None,
    'blockFormat': 1,
    'blockSize': None,
    'blockStartPattern': None,
    'blockType': 'ShowOSPFNeighbors',
    'bootROMRequired': None,
    'changeDate': None,
    'changeEventData': None,
    'changedBy': 'N/A',
    'checksum': None,
    'childDeviceID': None,
    'columnName': None,
    'commands': None,
    'comments': None,
    'completeDate': None,
    'conditions': None,
    'configComments': None,
    'configExceptionID': None,
    'configHash': None,
    'configHashMode': None,
    'configID': None,
    'configPolicyDynamicScopeFilterCriteria': None,
    'configPolicyID': None,
    'configPolicyName': None,
    'configRuleID': None,
    'configRuleName': None,
    'configurationVersion': None,
    'configuredDuplex': None,
    'configuredSpeed': None,
    'consoleIPAddress': None,
    'consolePort': None,
    'consoleRealmName': None,
    'contact': None,
    'containingUserGroupID': None,
    'core': None,
    'coreID': None,
    'createDate': 'Sat Feb 01 15:21:57 UTC 2020',
    'createType': None,
    'createUserID': None,
    'createdBy': None,
    'crossReferenceTopologyDataID': None,
    'csvData': None,
    'csvGroupTask': None,
    'currentVLANNumber': None,
    'customDataID': None,
    'customFieldDefinitionID': None,
    'customFieldID': None,
    'customFieldName': None,
    'customFieldValue': None,
    'customModel': 0,
    'customScriptID': None,
    'data': None,
    'dataBlock': None,
    'description': None,
    'destinationDeviceID': None,
    'deviceACLID': None,
    'deviceAccessLogID': 57721,
    'deviceAuthenticationID': None,
    'deviceCount': None,
    'deviceCustom1': None,
    'deviceCustom2': None,
    'deviceCustom3': None,
    'deviceCustom4': None,
    'deviceCustom5': None,
    'deviceCustom6': None,
    'deviceDataCustom1': None,
    'deviceDataCustom2': None,
    'deviceDataCustom3': None,
    'deviceDataCustom4': None,
    'deviceDataCustom5': None,
    'deviceDataCustom6': None,
    'deviceDataID': 89901,
    'deviceFamily': None,
    'deviceFamilyName': None,
    'deviceGroup1ID': None,
    'deviceGroup2ID': None,
    'deviceGroup3ID': None,
    'deviceGroupCustom1': None,
    'deviceGroupCustom2': None,
    'deviceGroupCustom3': None,
    'deviceGroupCustom4': None,
    'deviceGroupCustom5': None,
    'deviceGroupCustom6': None,
    'deviceGroupID': None,
    'deviceGroupName': None,
    'deviceGroups': None,
    'deviceID': 6641,
    'deviceIP': None,
    'deviceModuleID': None,
    'deviceName': None,
    'devicePortID': None,
    'deviceRelationshipID': None,
    'deviceSoftwareImageID': None,
    'deviceTopologyDataID': None,
    'deviceType': None,
    'deviceVTPID': None,
    'deviceViewID': None,
    'deviceViewIDChanged': None,
    'deviceVlanInfoID': None,
    'devices': None,
    'disclosureDate': None,
    'displayName': None,
    'distinguishedName': None,
    'domainName': None,
    'driverLookupID': None,
    'driverName': None,
    'driverNames': None,
    'driverRequired': None,
    'drivers': None,
    'duplexMismatchDetected': None,
    'duration': None,
    'durationStr': None,
    'dynamicFilter': None,
    'dynamicFilterXML': None,
    'emailAddress': None,
    'endDate': None,
    'endRange': None,
    'evaluationLogic': None,
    'eventClass': None,
    'eventData': None,
    'eventDate': None,
    'eventDeviceID': None,
    'eventID': None,
    'eventTaskID': None,
    'eventText': None,
    'eventType': None,
    'eventUserID': None,
    'exactOrder': None,
    'exceptionType': None,
    'excludeFromPoll': None,
    'expensive': None,
    'expirationDate': None,
    'externalChangeRequestID': None,
    'failedChildCount': None,
    'failureType': None,
    'feedSource': None,
    'fieldDataType': None,
    'fieldID': None,
    'fieldLabel': None,
    'fieldName': None,
    'fieldValues': None,
    'firmwareVersion': None,
    'firstName': None,
    'firstSeen': None,
    'flags': None,
    'flashMemory': None,
    'flashRAMRequired': None,
    'forceSave': None,
    'freePorts': None,
    'geographicalLocation': None,
    'grantedResources': None,
    'groups': None,
    'handle': None,
    'hardwareRequired': None,
    'hardwareRevision': None,
    'hashAlg': None,
    'hierarchyLayer': None,
    'hostName': None,
    'id': None,
    'idValue': None,
    'imageName': None,
    'imagePath': None,
    'imageSetName': None,
    'imageSize': None,
    'importance': None,
    'inCompliance': None,
    'inUse': None,
    'interceptorLogCustom1': None,
    'interceptorLogCustom2': None,
    'interceptorLogCustom3': None,
    'interceptorLogCustom4': None,
    'interceptorLogCustom5': None,
    'interceptorLogCustom6': None,
    'interceptorLogID': None,
    'ipAddress': None,
    'ipAddresses': None,
    'ipCustom1': None,
    'ipCustom2': None,
    'ipCustom3': None,
    'ipCustom4': None,
    'ipCustom5': None,
    'ipCustom6': None,
    'ipID': None,
    'ipMask': None,
    'ipName': None,
    'ipPriority': None,
    'ipType': None,
    'ipValue': None,
    'isConfigChange': None,
    'isDynamic': None,
    'isIntegrationEnabled': None,
    'isLookupSkipped': None,
    'isParent': None,
    'isPolicyScope': None,
    'isUsingSsl': None,
    'lastAccessAttemptDate': None,
    'lastAccessAttemptStatus': None,
    'lastAccessSuccessDate': None,
    'lastConfigChangeUserID': None,
    'lastConfigPolicyCheckedDate': None,
    'lastDuplexDataUpdate': None,
    'lastImportDate': None,
    'lastLoginDate': None,
    'lastModifiedAccessLogID': None,
    'lastModifiedDate': 'Sat Feb 01 15:22:06 UTC 2020',
    'lastModifiedUserID': None,
    'lastModifyDate': None,
    'lastModifyUserID': None,
    'lastName': None,
    'lastRecordModifiedDate': None,
    'lastSeen': None,
    'lastSnapshotAttemptDate': None,
    'lastSnapshotAttemptStatus': None,
    'lastSnapshotDate': None,
    'lastSnapshotSuccessDate': None,
    'lastTopologyDataUpdate': None,
    'lastUpdated': None,
    'lastUsedAuthenticationID': None,
    'latestSoftwareHistoryID': None,
    'latestStartupRunningDiffer': None,
    'limitSearchbyDeviceGroup': None,
    'limitSearchbyPartition': None,
    'mCreateDate': None,
    'mCustomServiceTypes': None,
    'mDeviceID': None,
    'mDevicePropertyID': None,
    'mLastModifiedDate': None,
    'mServiceTypes': None,
    'm_appliesTo': None,
    'm_buildNum': None,
    'm_comments': None,
    'm_coreHostname': None,
    'm_coreID': None,
    'm_coreRMIPort': None,
    'm_databaseHostname': None,
    'm_databaseIdentifier': None,
    'm_databasePort': None,
    'm_defaultDeviceGroupID': None,
    'm_description': None,
    'm_deviceGroupID': None,
    'm_enabled': None,
    'm_isMasterDef': None,
    'm_lastModifiedDate': None,
    'm_managingCoreID': None,
    'm_name': None,
    'm_owningCoreID': None,
    'm_realmName': None,
    'm_replicationAdminUser': None,
    'm_replicationPassword': None,
    'm_siteID': None,
    'm_status': None,
    'm_timezoneOffset': None,
    'm_userName': None,
    'm_version': None,
    'm_viewID': None,
    'm_viewName': None,
    'macAddress': None,
    'managementStatus': None,
    'managerUserID': None,
    'managingCoreID': None,
    'maskedSize': None,
    'maxVLANNumber': None,
    'maxWaitTime': None,
    'maxWaitTimeType': None,
    'md5Digest': None,
    'memory': None,
    'messageTo': None,
    'metadataID': None,
    'metadataName': None,
    'model': None,
    'modelDataName': None,
    'modelRequired': None,
    'modemNumber': None,
    'modifiable': None,
    'moduleCustom1': None,
    'moduleCustom2': None,
    'moduleCustom3': None,
    'moduleCustom4': None,
    'moduleCustom5': None,
    'moduleCustom6': None,
    'moduleDescription': None,
    'moduleModel': None,
    'moduleOS': None,
    'mostRecent': None,
    'mostRecentConfigID': None,
    'mtu': None,
    'nATIPAddress': None,
    'nATRealmName': None,
    'naIntegrationUser': None,
    'name': None,
    'nativeVlan': None,
    'negotiatedDuplex': None,
    'negotiatedSpeed': None,
    'networkAddressStart': None,
    'nnmiHostName': None,
    'nnmiIntegrationID': None,
    'nnmiNodeUUID': None,
    'nnmiPassword': None,
    'nnmiPort': None,
    'nnmiSystemID': None,
    'nnmiUser': None,
    'noPrune': None,
    'operand': None,
    'operatingMode': None,
    'operatorName': None,
    'originatingDeviceID': None,
    'paddedIp': None,
    'parameters': None,
    'parentDeviceGroupID': None,
    'parentIdentifier': None,
    'parentModuleID': None,
    'parentTaskID': None,
    'partitionCount': None,
    'partitions': None,
    'password': None,
    'passwordLastModifiedDate': None,
    'passwordOption': None,
    'pattern': None,
    'pendingChildCount': None,
    'performACLParsing': None,
    'policyImportance': None,
    'policyInCompliance': None,
    'portAllows': None,
    'portChannelID': None,
    'portChannelName': None,
    'portCustom1': None,
    'portCustom2': None,
    'portCustom3': None,
    'portCustom4': None,
    'portCustom5': None,
    'portCustom6': None,
    'portName': None,
    'portState': None,
    'portStatus': None,
    'portType': None,
    'postCheckExpression': None,
    'powerScriptID': None,
    'preCheckExpression': None,
    'primaryFQDN': None,
    'primaryIPAddress': None,
    'priority': None,
    'privilegeLevel': None,
    'processor': None,
    'pruningMode': None,
    'putInServiceDate': None,
    'rOMVersion': None,
    'realmName': None,
    'redirectLocation': None,
    'refreshToken': None,
    'refreshTokenID': None,
    'relationshipTypeID': None,
    'relationshipTypeName': None,
    'remoteDeviceID': None,
    'remoteDevicePortID': None,
    'remoteSasServerID': None,
    'remoteSasServerInterfaceID': None,
    'repeatCount': None,
    'repeatEndDate': None,
    'repeatInterval': None,
    'repeatType': None,
    'repeatWeekday': None,
    'required': None,
    'requiredUser': None,
    'requiresReferenceUpdate': None,
    'requiresUpdate': None,
    'reservationEndDate': None,
    'reservedDuration': None,
    'reservedDurationType': None,
    'resourceIdentityID': None,
    'resourceIdentityPoolID': None,
    'result': None,
    'resultConfigID': None,
    'retryCount': None,
    'retryInterval': None,
    'roleID': None,
    'roleName': None,
    'roleType': None,
    'rollBackScriptVO': None,
    'ruleConditionID': None,
    'ruleConditionOrder': None,
    'ruleName': None,
    'rulePattern': None,
    'rulePriority': None,
    'ruleType': None,
    'runASAP': None,
    'runRollBack': None,
    'runType': None,
    'runningChildTaskId': None,
    'salt': None,
    'saltmode': None,
    'saveFavoriteLink': None,
    'saveTask': None,
    'saveTemplate': None,
    'scheduleDate': None,
    'scheduleTaskID': None,
    'scope': None,
    'script': None,
    'scriptMode': None,
    'scriptName': None,
    'scriptType': None,
    'scriptVO': None,
    'scripts': None,
    'serialNumber': None,
    'sessionData': None,
    'sessionType': None,
    'shared': None,
    'siteID': None,
    'siteName': None,
    'slot': None,
    'slotNumber': None,
    'slotType': None,
    'softwareVersion': None,
    'solution': None,
    'sourceDeviceDataID': None,
    'startDate': None,
    'startRange': None,
    'status': None,
    'stopOnFail': None,
    'subTask': None,
    'subTasks': None,
    'subnetBitCount': None,
    'succeededChildCount': None,
    'systemTask': None,
    'tFTPServerIPAddress': None,
    'tableName': None,
    'tag': None,
    'taskCustom1': None,
    'taskCustom2': None,
    'taskCustom3': None,
    'taskCustom4': None,
    'taskCustom5': None,
    'taskCustom6': None,
    'taskData': None,
    'taskName': None,
    'taskType': None,
    'taskUserID': None,
    'temporaryVlanName': None,
    'ticketNumber': None,
    'timeZone': None,
    'topologyDataType': None,
    'totalPorts': None,
    'treatNullAsEmpty': None,
    'unmanagedDate': None,
    'uptime': None,
    'uptimeStoredDate': None,
    'useAaaLoginForProxy': None,
    'useLatest': None,
    'useRegex': None,
    'useRegexp': None,
    'usedToAccess': None,
    'userCustom1': None,
    'userCustom2': None,
    'userCustom3': None,
    'userCustom4': None,
    'userCustom5': None,
    'userCustom6': None,
    'userGeneratedChange': None,
    'userGroups': None,
    'userID': None,
    'userName': None,
    'userPassword': None,
    'userPasswordUnhashed': None,
    'variableData': None,
    'variables': None,
    'vendor': None,
    'vendorAdvisoryURL': None,
    'vendorSolutionURL': None,
    'vlanID': None,
    'vlanName': None,
    'vlanPortType': None,
    'vlanPrivate': None,
    'vlanStatus': None,
    'vlanType': None,
    'volatileRAMRequired': None,
    'vtpTrapsGeneration': None,
    'vtpV2Mode': None,
    'vtpVersion': None

**Comment by newlandk** [comment]
My PR #20 should fix list_user. What is the expected output with your diagnostic that isn’t in the list? What is the output if you run the command in the CLI?

**Comment by anousonevongsouvanTR** [comment]
Hello there, thanks for your quick response:

Here’s the command and output from HPNA cli:

NA>list diagnostic -host testdevice -diagnostic "NA OSPF Neighbors"
200 OK: Generic Succeeded
+-------+-----------------------+
| ID    | CreateDate            |
+-------+-----------------------+
| 93511 | 2020-02-29 05:16:29.0 |
| 89901 | 2020-02-01 15:21:57.0 |
+-------+-----------------------+
COMMAND COMPLETED
NA>


There are other commands such as “list diagnostic all”:

NA>list diagnostic all
200 OK: Generic Succeeded
+-------+---------------+-----------------------+
| ID    | Access Log ID | Create Date           |
+-------+---------------+-----------------------+
| 4141  | 6911          | 2019-11-19 11:07:59.0 |
| 4121  | 6911          | 2019-11-19 11:07:59.0 |
| 4901  | 7021          | 2019-11-19 11:09:04.0 |
| 5731  | 7291          | 2019-11-19 11:10:19.0 |
| 6021  | 7671          | 2019-11-19 11:16:58.0 |
| 5952  | 7482          | 2019-11-19 12:00:23.0 |
| 7872  | 8562          | 2019-11-19 23:50:51.0 |
| 7892  | 8562          | 2019-11-19 23:50:51.0 |
| 7902  | 8562          | 2019-11-19 23:50:51.0 |
| 7912  | 8562          | 2019-11-19 23:50:51.0 |
| 7962  | 8592          | 2019-11-19 23:50:52.0 |
| 7972  | 8592          | 2019-11-19 23:50:52.0 |
| 7982  | 8592          | 2019-11-19 23:50:52.0 |
| 4192  | 6502          | 2019-11-19 11:08:11.0 |
| 4731  | 6991          | 2019-11-19 11:08:52.0 |
| 4821  | 7001          | 2019-11-19 11:09:00.0 |
| 4841  | 7011          | 2019-11-19 11:09:03.0 |
| 5891  | 7461          | 2019-11-19 11:16:41.0 |
| 5971  | 7561          | 2019-11-19 11:16:53.0 |
| 7992  | 8592          | 2019-11-19 23:50:52.0 |
| 8002  | 8592          | 2019-11-19 23:50:52.0 |
| 5661  | 7281          | 2019-11-19 11:10:17.0 |
| 5681  | 7281          | 2019-11-19 11:10:17.0 |
| 6001  | 7601          | 2019-11-19 11:16:55.0 |
| 8032  | 8612          | 2019-11-19 23:50:53.0 |
| 8142  | 8652          | 2019-11-19 23:50:54.0 |
| 5641  | 7281          | 2019-11-19 11:10:17.0 |
| 8232  | 8672          | 2019-11-19 23:50:55.0 |
| 8242  | 8662          | 2019-11-19 23:50:55.0 |
…….

**Comment by newlandk** [comment]
@anousonevongsouvanTR If you search for 89901 you can see that it matches the output from the SOAP API in your first post. The create date is there too, just with a little different date format.

'deviceDataID': 89901 & Sat Feb 01 15:21:57 UTC 2020 (from your first post)
| 89901 | 2020-02-01 15:21:57.0 | from the CLI output.

I've noticed it provides back a LOT of extra data and haven't had the time to understand if it's due to the API response or the module itself. If you do a little iterator over the responses and remove all of the None type values it's a little easier to see useful data.

**Comment by anousonevongsouvanTR** [comment]
Oh yes, you are absolutely correct, my mistake, I should of looked closer!

**Comment by newlandk** [comment]
@spenceation I think this is able to be closed at this point. It appears that the primary concerns were that the results have many presumably unneeded fields and that MFNA responds with new response codes that were not in the original list.

With your familiarity on the MFNA SOAP API, is there a good way to clean up the response or do you believe this is at closure?

Thank you for the great module getting us all started!

**Comment by anousonevongsouvanTR** [comment]
Yes it can be closed.  I am able to clean up the data.  I might have one more issue to run by you, but I will open another ticket if I cannot figure it out, but might have to do with my lack of python skills.  Thanks for your timely responses.

Nunu

**Comment by newlandk** [comment]
@anousonevongsouvanTR I am not a primary contributor to this project, but happy to help where I can. IMO you can close this issue. I'm watching the project and will chime in where I can if you have any questions!
