### ISSUE TITLE
HPNA List diagnostics response error 

### ISSUE THREAD

**Issue by anousonevongsouvanTR** [spenceation/hpnapy#22]
Hello there, I am executing a diagnostic command thru my python script:

t = hpna.list_diagnostic(host="test-device", diagnostic="NA OSPF Neighbors")
print(t)

I am receiving an http 200 OK message from the HPNA server when I looked at my tcpdump pcap.  However, I think thru the hpna.py code, it's erroring out, and stopping the entire script from running.  The issue I think is that the device itself doesn't have any "NA OSPF Neighbors" diagnostics associated with it, so no data ever comes back.  However, it is still a successful 200 ok http transaction that gets returned.  Executing below thru HPNA cli shows a 200 OK but no results to display:

NA>list diagnostic -host test-device -diagnostic "NA OSPF Neighbors"
200 OK: Generic Succeeded
No results to display.
COMMAND COMPLETED

Error message below thru the API:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/hpnapy/hpnapy.py", line 1113, in _get_extracted_result_set
    if api_result.ResultSet.Row:
AttributeError: 'NoneType' object has no attribute 'Row'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hpna_retrieve.py", line 49, in <module>
    t = hpna.list_diagnostic(host="test-device", diagnostic="NA OSPF Neighbors")
  File "/usr/local/lib/python3.6/site-packages/hpnapy/hpnapy.py", line 438, in list_diagnostic
    return self._connector.execute_multi_result_call("list_diagnostic", **kwargs)
  File "/usr/local/lib/python3.6/site-packages/hpnapy/hpnapy.py", line 1146, in execute_multi_result_call
    extracted_result = self._get_extracted_result_set(api_response)
  File "/usr/local/lib/python3.6/site-packages/hpnapy/hpnapy.py", line 1116, in _get_extracted_result_set
    self._raise_hpna_fault_exception()
  File "/usr/local/lib/python3.6/site-packages/hpnapy/hpnapy.py", line 1100, in _raise_hpna_fault_exception
    raise HPNAQueryError("An error occurred during execution.")
hpnapy.exceptions.HPNAQueryError: An error occurred during execution.

I am trying to dump out all sorts of diagnostic looping thru an extracted lists of hosts thru the API, however to determine if any host doesn't have a specific diagnostic ran on it, I would need to figure out logic to exclude it.  I was hoping to somehow have a way to ignore the error and not print it out, and have the script keep going, or have it accept the 200 ok message, and have no data coming back should be a successful transaction?

**Comment by spenceation** [comment]
@anousonevongsouvanTR , I agree this should instead return an empty result and allow the calling function to handle the results. I've changed it to instead return an empty list.

**Comment by anousonevongsouvanTR** [comment]
I looked at the changes that was done, and I think I did the same on the hpnapy.py, but I get an error when running my python script.

https://github.com/spenceation/hpnapy/pull/23/commits/8bf8e382466c15f77c2e4de522175eb33736cc4a

Traceback (most recent call last):
  File "/home/m0127005/2-hpna-retrieve.py", line 5, in <module>
    from hpnapy import NAInterface
  File "/usr/local/lib/python3.6/site-packages/hpnapy/__init__.py", line 24, in <module>
    from .hpnapy import NAInterface
  File "/usr/local/lib/python3.6/site-packages/hpnapy/hpnapy.py", line 1127
    pass None
            ^
SyntaxError: invalid syntax

**Comment by spenceation** [comment]
@anousonevongsouvanTR I think you grabbed that before I fixed that. That should just be a pass, not pass none.

I put 1.0.7 on pypi, so hopefully that will address your issue.

 When possible, could you download that version and test?

**Comment by anousonevongsouvanTR** [comment]
Hi there, I am unable to see the latest version using ‘pip install hpnapy’.  Was there another way you wanted me to install this?

Requirement already satisfied: hpnapy in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: requests>=1.0.0 in /usr/local/lib/python3.6/site-packages (from hpnapy)
Requirement already satisfied: zeep>=3.0.0 in /usr/local/lib/python3.6/site-packages (from hpnapy)
Requirement already satisfied: urllib3>=1.0.0 in /usr/local/lib/python3.6/site-packages (from hpnapy)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=1.0.0->hpnapy)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=1.0.0->hpnapy)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=1.0.0->hpnapy)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from zeep>=3.0.0->hpnapy)
Requirement already satisfied: requests-toolbelt>=0.7.1 in /usr/local/lib/python3.6/site-packages (from zeep>=3.0.0->hpnapy)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib64/python3.6/site-packages (from zeep>=3.0.0->hpnapy)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/site-packages (from zeep>=3.0.0->hpnapy)
Requirement already satisfied: cached-property>=1.3.0 in /usr/local/lib/python3.6/site-packages (from zeep>=3.0.0->hpnapy)
Requirement already satisfied: defusedxml>=0.4.1 in /usr/local/lib/python3.6/site-packages (from zeep>=3.0.0->hpnapy)
Requirement already satisfied: isodate>=0.5.4 in /usr/local/lib/python3.6/site-packages (from zeep>=3.0.0->hpnapy)
Requirement already satisfied: attrs>=17.2.0 in /usr/local/lib/python3.6/site-packages (from zeep>=3.0.0->hpnapy)
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python3.6/site-packages (from zeep>=3.0.0->hpnapy)

**Comment by spenceation** [comment]
You will need to use the `--upgrade` flag, or else it won't upgrade.

You can try `pip install --upgrade hpnapy`

**Comment by anousonevongsouvanTR** [comment]
I was able to upgrade, but I ran into this issue below.  My script is calling a device group.  Below is my code:

Traceback (most recent call last):
  File "/home/xxxxxxxxxxxxx/2-hpna-retrieve.py", line 50, in <module>
    s = pd.Series(host, devicedataid) #converts variable a to a Pandas series
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/series.py", line 215, in __init__
    index = ensure_index(index)
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 5358, in ensure_index
    return Index(index_like)
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 422, in __new__
    raise cls._scalar_data_error(data)
TypeError: Index(...) must be called with a collection of some kind, '99541' was passed

#!/usr/bin/python3

# import python libraries
import sys
from hpnapy import NAInterface
import sys, getopt
import subprocess
import re
import os
import tempfile
import pandas as pd
import time

# Initialize HPNA API connection
hpna = NAInterface("xxxxxxxxxxxxxxxxxxxxxxxxx", ssl_verify=False)
hpna.login('xxxxxxxx', 'xxxxx')

# Variable that iterates a list of devices for selected group
list_devices = str(hpna.list_device(group=sys.argv[1]))

### Start of Loop ###

# Loops thru the selected device group and finds the hostName line. It will then remove unnecessary characters for further processing
for line in list_devices.split("\n"):
  if re.search("hostName", line): #find line that contains hostName
   device = re.sub('\'', '', line) #next lines begins to clean up found line
   device = re.sub(',', '', device)
   device = re.sub('hostName: ', '', device)
   device = device.strip()

# for each host, get the diagnostic IDs and set it as a variable
   for host in device.split("\n"):
    diagnosticid = str(hpna.list_diagnostic(host=host, diagnostic=sys.argv[2]))

# for each diagnostic ID, finds the creation date of the diagnostic for each host. It will then remove unnecessary characters for further processing
    for line in diagnosticid.split("\n"):
      if re.search("createDate", line): #find line that contains createDate
       createdate = re.sub('\'', '', line) #next lines begins to clean up found line
       createdate = re.sub(',', '', createdate)
       createdate = re.sub('createDate: ', '', createdate)
       createdate = createdate.strip()

# for each diagnostic ID, finds the deviceDataID. It will then remove unnecessary characters for further processing
      if re.search("deviceDataID", line): #find line that contains deviceDataID
       devicedataid = re.sub('\'', '', line) #next lines begins to clean up found line
       devicedataid = re.sub(',', '', devicedataid)
       devicedataid = re.sub('deviceDataID: ', '', devicedataid)
       devicedataid = devicedataid.strip()
#       print(host, devicedataid, createdate)
       s = pd.Series(host, devicedataid) #converts variable a to a Pandas series
       s = str(s.head(1).to_string(index=False, header=False).strip()) #selects latest diagnostic id
       print(s)
# for each devicedata ID, finally show the diagnostic content
       for line in devicedataid.split("\n"):
        diagnosticshow = str(hpna.show_diagnostic(id=line))
        file_object_write = open(f'{host}-arp', "w")
        for line in diagnosticshow.split("\n"):
         print(line.strip(), file = file_object_write)
#        print(createdate, file = file_object_write)

### End of Loop ###

**Comment by anousonevongsouvanTR** [comment]
Ignore that, something in my pandas section.  I thought it was working earlier, checking..


From: Vongsouvan, Anousone (TR Tech, Content & Ops)
Sent: Wednesday, March 11, 2020 9:06 AM
To: spenceation/hpnapy <reply@reply.github.com>; spenceation/hpnapy <hpnapy@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [spenceation/hpnapy] HPNA List diagnostics response error (#22)

I was able to upgrade, but I ran into this issue below.  My script is calling a device group.  Below is my code:

Traceback (most recent call last):
  File "/home/xxxxxxxxxxxxx/2-hpna-retrieve.py", line 50, in <module>
    s = pd.Series(host, devicedataid) #converts variable a to a Pandas series
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/series.py", line 215, in __init__
    index = ensure_index(index)
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 5358, in ensure_index
    return Index(index_like)
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 422, in __new__
    raise cls._scalar_data_error(data)
TypeError: Index(...) must be called with a collection of some kind, '99541' was passed

#!/usr/bin/python3

# import python libraries
import sys
from hpnapy import NAInterface
import sys, getopt
import subprocess
import re
import os
import tempfile
import pandas as pd
import time

# Initialize HPNA API connection
hpna = NAInterface("xxxxxxxxxxxxxxxxxxxxxxxxx", ssl_verify=False)
hpna.login('xxxxxxxx', 'xxxxx')

# Variable that iterates a list of devices for selected group
list_devices = str(hpna.list_device(group=sys.argv[1]))

### Start of Loop ###

# Loops thru the selected device group and finds the hostName line. It will then remove unnecessary characters for further processing
for line in list_devices.split("\n"):
  if re.search("hostName", line): #find line that contains hostName
   device = re.sub('\'', '', line) #next lines begins to clean up found line
   device = re.sub(',', '', device)
   device = re.sub('hostName: ', '', device)
   device = device.strip()

# for each host, get the diagnostic IDs and set it as a variable
   for host in device.split("\n"):
    diagnosticid = str(hpna.list_diagnostic(host=host, diagnostic=sys.argv[2]))

# for each diagnostic ID, finds the creation date of the diagnostic for each host. It will then remove unnecessary characters for further processing
    for line in diagnosticid.split("\n"):
      if re.search("createDate", line): #find line that contains createDate
       createdate = re.sub('\'', '', line) #next lines begins to clean up found line
       createdate = re.sub(',', '', createdate)
       createdate = re.sub('createDate: ', '', createdate)
       createdate = createdate.strip()

# for each diagnostic ID, finds the deviceDataID. It will then remove unnecessary characters for further processing
      if re.search("deviceDataID", line): #find line that contains deviceDataID
       devicedataid = re.sub('\'', '', line) #next lines begins to clean up found line
       devicedataid = re.sub(',', '', devicedataid)
       devicedataid = re.sub('deviceDataID: ', '', devicedataid)
       devicedataid = devicedataid.strip()
#       print(host, devicedataid, createdate)
       s = pd.Series(host, devicedataid) #converts variable a to a Pandas series
       s = str(s.head(1).to_string(index=False, header=False).strip()) #selects latest diagnostic id
       print(s)
# for each devicedata ID, finally show the diagnostic content
       for line in devicedataid.split("\n"):
        diagnosticshow = str(hpna.show_diagnostic(id=line))
        file_object_write = open(f'{host}-arp', "w")
        for line in diagnosticshow.split("\n"):
         print(line.strip(), file = file_object_write)
#        print(createdate, file = file_object_write)

### End of Loop ###

**Comment by anousonevongsouvanTR** [comment]
Ok, it looks like I am still getting the same error:

  File "/home/xxxxxxxxxxx/hpnapy/hpnapy.py", line 1113, in _get_extracted_result_set
    if api_result.ResultSet.Row:
AttributeError: 'NoneType' object has no attribute 'Row'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxxxxxxxxxxx/test-hpna.py", line 23, in <module>
    t = hpna.list_diagnostic(host="test-device", diagnostic="NA OSPF Neighbors")
  File "/home/xxxxxxxxx/hpnapy/hpnapy.py", line 438, in list_diagnostic
    return self._connector.execute_multi_result_call("list_diagnostic", **kwargs)
  File "/home/xxxxxxxxxxxxxx/hpnapy/hpnapy.py", line 1146, in execute_multi_result_call
    extracted_result = self._get_extracted_result_set(api_response)
  File "/home/xxxxxxxxxxxxxxx/hpnapy/hpnapy.py", line 1116, in _get_extracted_result_set
    self._raise_hpna_fault_exception()
  File "/home/xxxxxxxxxxxxx/hpnapy/hpnapy.py", line 1100, in _raise_hpna_fault_exception
    raise HPNAQueryError("An error occurred during execution.")

Script below:

#!/usr/bin/python3

import sys
from hpnapy import NAInterface
import sys, getopt
import subprocess
import re
import os
import tempfile
import pandas as pd
import time
from contextlib import suppress

# Initialize our interface
hpna = NAInterface("http://xxxxxxxxxxxxxxxxx", ssl_verify=False)
hpna.login(xxxxxxxxxxxxxxxxxxxx)

t = hpna.list_diagnostic(host="test-device", diagnostic="NA OSPF Neighbors")
print(t)


From: Vongsouvan, Anousone (TR Tech, Content & Ops)
Sent: Wednesday, March 11, 2020 9:17 AM
To: spenceation/hpnapy <reply@reply.github.com>; spenceation/hpnapy <hpnapy@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [spenceation/hpnapy] HPNA List diagnostics response error (#22)

Ignore that, something in my pandas section.  I thought it was working earlier, checking..


From: Vongsouvan, Anousone (TR Tech, Content & Ops)
Sent: Wednesday, March 11, 2020 9:06 AM
To: spenceation/hpnapy <reply@reply.github.com<mailto:reply@reply.github.com>>; spenceation/hpnapy <hpnapy@noreply.github.com<mailto:hpnapy@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [spenceation/hpnapy] HPNA List diagnostics response error (#22)

I was able to upgrade, but I ran into this issue below.  My script is calling a device group.  Below is my code:

Traceback (most recent call last):
  File "/home/xxxxxxxxxxxxx/2-hpna-retrieve.py", line 50, in <module>
    s = pd.Series(host, devicedataid) #converts variable a to a Pandas series
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/series.py", line 215, in __init__
    index = ensure_index(index)
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 5358, in ensure_index
    return Index(index_like)
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 422, in __new__
    raise cls._scalar_data_error(data)
TypeError: Index(...) must be called with a collection of some kind, '99541' was passed

#!/usr/bin/python3

# import python libraries
import sys
from hpnapy import NAInterface
import sys, getopt
import subprocess
import re
import os
import tempfile
import pandas as pd
import time

# Initialize HPNA API connection
hpna = NAInterface("xxxxxxxxxxxxxxxxxxxxxxxxx", ssl_verify=False)
hpna.login('xxxxxxxx', 'xxxxx')

# Variable that iterates a list of devices for selected group
list_devices = str(hpna.list_device(group=sys.argv[1]))

### Start of Loop ###

# Loops thru the selected device group and finds the hostName line. It will then remove unnecessary characters for further processing
for line in list_devices.split("\n"):
  if re.search("hostName", line): #find line that contains hostName
   device = re.sub('\'', '', line) #next lines begins to clean up found line
   device = re.sub(',', '', device)
   device = re.sub('hostName: ', '', device)
   device = device.strip()

# for each host, get the diagnostic IDs and set it as a variable
   for host in device.split("\n"):
    diagnosticid = str(hpna.list_diagnostic(host=host, diagnostic=sys.argv[2]))

# for each diagnostic ID, finds the creation date of the diagnostic for each host. It will then remove unnecessary characters for further processing
    for line in diagnosticid.split("\n"):
      if re.search("createDate", line): #find line that contains createDate
       createdate = re.sub('\'', '', line) #next lines begins to clean up found line
       createdate = re.sub(',', '', createdate)
       createdate = re.sub('createDate: ', '', createdate)
       createdate = createdate.strip()

# for each diagnostic ID, finds the deviceDataID. It will then remove unnecessary characters for further processing
      if re.search("deviceDataID", line): #find line that contains deviceDataID
       devicedataid = re.sub('\'', '', line) #next lines begins to clean up found line
       devicedataid = re.sub(',', '', devicedataid)
       devicedataid = re.sub('deviceDataID: ', '', devicedataid)
       devicedataid = devicedataid.strip()
#       print(host, devicedataid, createdate)
       s = pd.Series(host, devicedataid) #converts variable a to a Pandas series
       s = str(s.head(1).to_string(index=False, header=False).strip()) #selects latest diagnostic id
       print(s)
# for each devicedata ID, finally show the diagnostic content
       for line in devicedataid.split("\n"):
        diagnosticshow = str(hpna.show_diagnostic(id=line))
        file_object_write = open(f'{host}-arp', "w")
        for line in diagnosticshow.split("\n"):
         print(line.strip(), file = file_object_write)
#        print(createdate, file = file_object_write)

### End of Loop ###

**Comment by anousonevongsouvanTR** [comment]
Hello there, I have not heard any updates on this issue, but I was able to comment out a few lines so that it wouldn't error out.  This allowed the queries to keep going regardless of errors coming back.  

def _validate_api_response(self, api_response):
        try:
            if api_response.Status in ['200', '201', '204', '221', '501', '503', '511']:
                return
        except AttributeError:
            self._raise_hpna_fault_exception()
        #raise HPNAQueryError("HP NA API Execution error: Status:{0}, Text:{1}".format(
        #    api_response.Status, api_response.Text))

**Comment by newlandk** [comment]
@anousonevongsouvanTR if you run the code with that not commented out. What is the traceback you are receiving? Does it provide a status code? (or is it the NoneType error?)

When I've hit that in the past it was due to different status codes being returned that were valid, but not accounted for in the list. (specifically 201 and 511)

https://github.com/spenceation/hpnapy/blob/be1f7476103cf03f0a16a2bb7d4d821959c3ca02/hpnapy/hpnapy.py#L1102-L1109

Additionally, can you provide a `pip freeze` of the environment you are running your script in to validate the version of hpnapy you are using?

**Comment by anousonevongsouvanTR** [comment]
I get a 503 operation failed error.  My script gets members of HPNA groups, and finds the diagnostics for each device.  I’ve noticed that when a device does not have a diagnostic id, I get this 503 error, but even when I specify the 503 in the exception list, it errors out

python3.6 hpna_arp.py '{"L3 ARP Mapping IOS - PROD":"Switch Port Mapping ARP Table IOS","L3 ARP Mapping NXOS - PROD":"Switch Port Mapping ARP Table NXOS"}'
Traceback (most recent call last):
  File "hpna_arp.py", line 40, in <module>
    diagnosticid = str(hpna.list_diagnostic(host=host, diagnostic=group_and_diag_name[item]))
  File "/usr/local/lib/python3.6/site-packages/hpnapy/hpnapy.py", line 438, in list_diagnostic
    return self._connector.execute_multi_result_call("list_diagnostic", **kwargs)
  File "/usr/local/lib/python3.6/site-packages/hpnapy/hpnapy.py", line 1145, in execute_multi_result_call
    api_response = self._get_api_query_response(command_to_call, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/hpnapy/hpnapy.py", line 1136, in _get_api_query_response
    self._validate_api_response(api_response)
  File "/usr/local/lib/python3.6/site-packages/hpnapy/hpnapy.py", line 1109, in _validate_api_response
    api_response.Status, api_response.Text))
hpnapy.exceptions.HPNAQueryError: HP NA API Execution error: Status:503 Operation Failed, Text:None


appdirs==1.4.3
attrs==19.3.0
cached-property==1.5.1
certifi==2019.11.28
chardet==3.0.4
defusedxml==0.6.0
furl==2.1.0
hpnapy==1.0.7
idna==2.9
ISE==0.1.2
isodate==0.6.0
lxml==4.5.0
numpy==1.18.1
orderedmultidict==1.0.1
pandas==1.0.1
passlib==1.7.2
python-dateutil==2.8.1
pytz==2019.3
requests==2.23.0
requests-toolbelt==0.9.1
six==1.14.0
urllib3==1.25.8
zeep==3.4.0

**Comment by newlandk** [comment]
@anousonevongsouvanTR

Based on a little testing, the only way I was able to reproduce a 503 from the MFNA API was by providing that query an invalid hostname. When reviewing your code I notice you are doing a lot of text parsing and that could cause issues if your parsing goofs a hostname and what is passed to MFNA doesn't actually exist.

I would highly recommend iterating over the responses from hpnapy instead of parsing the values out of the MFNA objects casted to strings like below.

```python
for e in hpna.list_device(group="some-group"):
    diagnostic_list = hpna.list_diagnostic(host="fakehost", diagnostic="MagicalNsosDiagnostic")))
    print(diagnostic_list)
```

You can iterate over the diagnostic results for a given list_diagnostic response using similar syntax as well.

**Comment by anousonevongsouvanTR** [comment]
Hello Kevin, thanks for your response.  I am able to consistently replicate the issue, and show that it is indeed the list_diagnostic command that is tripping on the hostname.  I get the hostname from the device group query, so I am thinking it’s not an issue with the script that is putting in bad hostnames.  I did track down to it actually HPNA have a duplicate device name.  It seems HPNA allows for duplicate device names, but when you try to query the name, it gives back a 503 error condition.
So I am thinking I can try to clean these issues up before hand, and keep a tight lid on others adding devices with duplicate names, or try to account for these 503 errors and keep rerunning my script picking up these errors, and omitting the devices that cause this.

Is there anything that can be done to account for those 503 errors, and just ignore them (I added it to the error list, but it doesn’t seem to take effect)?

Btw, I am reading thru your email, but can’t quite understand your explanation on how to get around this by changing my script.

**Comment by newlandk** [comment]
What I suggested will not solve your problem, but it is a more efficient and safer way to parse through the data that you are returning from MFNA.

If you are going to resolve this issue via strict prevention of duplicate entry names you should likely not catch 503s as they are legitimate errors from the platform and may end up causing more issues down the road if a 503 is thrown for another reason. If you want to skip them and move forward, you could handle them with a try/except within your own code and log the exceptions... IMO, I don't think it's really necessary for hpnapy to solve for what is essentially a problem with the way that MFNA handles duplicate hostname entires.

You other option would be to use the deviceId instead of the hostname to request the diagnostics as that is likely the primary key for the entry in MFNA and would not hit the same conflict as the one-to-many hostname to IDs you appear to be hitting.

**Comment by anousonevongsouvanTR** [comment]
Ok, that sounds great.  I think your suggestion of using the deviceid  might be my way to go.  I’ll try that, and I’ll close this issue.

**Comment by anousonevongsouvanTR** [comment]
closing issue, as it is an issue with MFNA
